[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/flights"
  to = "/.netlify/functions/flights"
  status = 200
  force = true

